### ISSUE TITLE
本地安装发生错误

### ISSUE THREAD

**Issue by shaobeipan** [seadfeng/cloudflare-proxy-sites#1]
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

**Comment by seadfeng** [comment]
不要理会这个WARNING,  本地调试配合 [/etc/hosts](url) (如果是windows路径不同) ；
npm run dev 运行后有个端口号，用`/etc/hosts`配置好的域名测试

**Comment by seadfeng** [comment]
> npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject. npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

不要理会这个WARNING, 本地调试配合 [/etc/hosts](https://github.com/seadfeng/cloudflare-proxy-sites/issues/url) (如果是windows 自行寻找路径) ；
npm run dev 运行后有个端口号，用/etc/hosts配置好的域名测试

**Comment by seadfeng** [comment]
> npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject. npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

更新了package.json, 你用新试试

**Comment by shaobeipan** [comment]
对方网站有cloudflare验证,可以使用吗

**Comment by seadfeng** [comment]
> 对方网站有cloudflare验证,可以使用吗

这个没有注意，主要看验证方式，多数验证应该是不行的，有没办法一起转发没有研究，初衷是给站点加速

**Comment by shaobeipan** [comment]
重新安装了依然提示上面的错误。
运行wrangler login  allow以后跳转到http://localhost:8976/上去。已经在index.js上添加域名。
﻿

**Comment by seadfeng** [comment]
> 重新安装了依然提示上面的错误。 运行wrangler login allow以后跳转到[http://localhost:8976/上去。已经在index.js上添加域名。](http://localhost:8976/%E4%B8%8A%E5%8E%BB%E3%80%82%E5%B7%B2%E7%BB%8F%E5%9C%A8index.js%E4%B8%8A%E6%B7%BB%E5%8A%A0%E5%9F%9F%E5%90%8D%E3%80%82)

`npm i -g wrangler@3.68.0` 尝试更新wrangler版本

如果不需要二次开发，不需要本地调试，直接deploy就行
