### ISSUE TITLE
能实现泛域名解析然后自动 proxy 吗，即不需添加固定的代理域名

### ISSUE THREAD

**Issue by goxofy** [seadfeng/cloudflare-proxy-sites#2]

**Comment by seadfeng** [comment]
你需要一个cloudflare pro账户，free的SSL不支持

**Comment by seadfeng** [comment]
> 你需要一个cloudflare pro账户，free的SSL不支持

补充一点，除非你不开SSL

**Comment by seadfeng** [comment]
> _No description provided._
你需要一个cloudflare pro账户，free的SSL不支持；
当然不开SSL也是可以的，支持泛域名解析

**Comment by goxofy** [comment]
> > _No description provided._
> > 你需要一个cloudflare pro账户，free的SSL不支持；
> > 当然不开SSL也是可以的，支持泛域名解析

如果有cloud flare pro 怎么配置呢

**Comment by seadfeng** [comment]
> > > _No description provided._
> > > 你需要一个cloudflare pro账户，free的SSL不支持；
> > > 当然不开SSL也是可以的，支持泛域名解析
> 
> 如果有cloud flare pro 怎么配置呢

*.your-domain.com
域名添加时直接泛域名
