### ISSUE TITLE
can I use this with a subdomain of a domain I already own? if yes, how?

### ISSUE THREAD

**Issue by raiden076** [seadfeng/cloudflare-proxy-sites#3]
![image](https://github.com/user-attachments/assets/f4137387-447f-4345-b361-ae99b7425d5c)

I have this personal domain, and can I use it with this subdomain?
if yes, how? 

thanks in advance

**Comment by seadfeng** [comment]
> ![image](https://private-user-images.githubusercontent.com/40303218/355415374-f4137387-447f-4345-b361-ae99b7425d5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDI0OTAsIm5iZiI6MTcyMjk0MjE5MCwicGF0aCI6Ii80MDMwMzIxOC8zNTU0MTUzNzQtZjQxMzczODctNDQ3Zi00MzQ1LWIzNjEtYWU5OWI3NDI1ZDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDExMDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1YzZkMjYxYzU1Y2MxZjRiZWJiOTY1ZjZmNTE5NDQ5ZDk2MWI1MjZmOGU1YTVkYzVlZDA2NjNhMzY4MTAxOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AV0AsQVQIjgyyWfyHQVe4mD-gU91GOZ-Ke0FUjOTtXY)
> 
> I have this personal domain, and can I use it with this subdomain? if yes, how?
> 
> thanks in advance

 Single domain reverse proxy. Try this Code

https://github.com/seadfeng/cloudflare-proxy-sites/blob/main/workers.dev/index.js

```js
// workers.dev/index.js
// replace to your proxy site domain
const proxySite = 'example.com';
```

**Comment by seadfeng** [comment]
> ![image](https://private-user-images.githubusercontent.com/40303218/355415374-f4137387-447f-4345-b361-ae99b7425d5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDQ0NDksIm5iZiI6MTcyMjk0NDE0OSwicGF0aCI6Ii80MDMwMzIxOC8zNTU0MTUzNzQtZjQxMzczODctNDQ3Zi00MzQ1LWIzNjEtYWU5OWI3NDI1ZDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDExMzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYjJiYzQ3NzFlZTRiNmE5MjA0YWYyNWUxZmM5NGUyZGIxMWE0NWVmNDc4M2MzODk4N2ZlZTVlZThhODZjMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HuT1gBN1i6pWoBvNtx4oAdgBeRhl0C2cquXc4P60XQ8)
> 
> I have this personal domain, and can I use it with this subdomain? if yes, how?
> 
> thanks in advance

Manual Cloudflare Setup Guide: 

https://github.com/seadfeng/cloudflare-proxy-sites/tree/main/workers.dev

**Comment by raiden076** [comment]
So with the subdomain,
I can't use the dynamic proxy?

Only a single domain is allowed?

**Comment by seadfeng** [comment]
> So with the subdomain, I can't use the dynamic proxy?
> 
> Only a single domain is allowed?

Dynamic proxy for Multi-Site:

You need to have your own domain. The proxy site will be automatically recognized based on the domain name. After deployment, you only need to add custom domains according to the rules. Configure the `ownDomain` variable when deploying.

```js
// index.js
// replace to your domain
const ownDomain = "example.com";
```

The domain consists of two parts: target domain and own domain. For example:

Proxy site address: https://www.proxysites.ai.serp.ing

- **target domain**: www.proxysites.ai

- **own domain**: serp.ing


Proxy site address: https://www.serpchecking.com.serp.ing/

- **target domain**: www.serpchecking.com

- **own domain**: serp.ing


Code: [index.js](https://github.com/seadfeng/cloudflare-proxy-sites/blob/main/index.js)

**Comment by raiden076** [comment]
Thanks for the detailed info,

What I was trying, can't be possible I see,
I was trying to use, "proxy.arkaprav0.in" as own domain,
And proxy, say facebook.com, 

I was aiming for "facebook.com.proxy.arkaprav0.in"

It doesn't look like that is happening,

Thanks anyway...

**Comment by seadfeng** [comment]
> Thanks for the detailed info,
> 
> What I was trying, can't be possible I see, I was trying to use, "proxy.arkaprav0.in" as own domain, And proxy, say facebook.com,
> 
> I was aiming for "facebook.com.proxy.arkaprav0.in"
> 
> It doesn't look like that is happening,
> 
> Thanks anyway...

const ownDomain = "proxy.arkaprav0.in";

Add Custom Domain `facebook.com.proxy.arkaprav0.in`:

![image](https://github.com/user-attachments/assets/eb9f0232-49b2-49de-9b3c-09298c26ab3d)

If you need full auto-recognition, you'll need a cloudflare pro account and to add a domain name to pan-resolve `*.arkaprav0.in`. 

In this case, you only need to add it once

**Comment by raiden076** [comment]
Thanks man,

I see I need a pro account for what I was aiming for, originally,
thanks for the clarification 

(I tried adding a custom wildcard cert generated with certbot, but damn cloudflare doesn't even allow uploading a custom one, not even in the pro plan, I need a business account 😴)
