### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by xiaopangzi13140** [seadfeng/cloudflare-proxy-sites#5]
谢谢这个程序，很好用。目前有两个问题，想请教一下大佬：
1、使用单域名模式，代理了youtube网站，视频无法播放
2、想把这个程序部署在自己的vps服务器上，请问应该如何操作呢

**Comment by seadfeng** [comment]
> 谢谢这个程序，很好用。目前有两个问题，想请教一下大佬： 1、使用单域名模式，代理了youtube网站，视频无法播放 2、想把这个程序部署在自己的vps服务器上，请问应该如何操作呢
1、这个不建议，GG 家的产品有反扒，代价较大；其次视频播放是跨域问题，你必须有代码基础。
2、vps  用[vercel版本](https://github.com/seadfeng/vercel-proxy-sites)，可以找下nextjs VPS部署教程

**Comment by seadfeng** [comment]
> 谢谢这个程序，很好用。目前有两个问题，想请教一下大佬： 1、使用单域名模式，代理了youtube网站，视频无法播放 2、想把这个程序部署在自己的vps服务器上，请问应该如何操作呢

1、这个不建议，GG 家的产品有反扒，代价较大；其次视频播放是跨域问题，你必须有代码基础。
2、vps 用[vercel版本](https://github.com/seadfeng/vercel-proxy-sites)，可以找下nextjs VPS部署教程
